version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements:
        - mkdocs==1.5.3
        - mkdocs-readthedocs-theme==1.2.0
        - pymdown-extensions==10.5
