site_name: ELP Parser
site_description: A PHP library for parsing ELP (eXe Learning Package) files
theme:
  name: readthedocs
  highlightjs: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage Guide: usage.md
  - API Reference: api.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list
  - md_in_html
